config/routes.rb
AxData::Application.routes.draw do
  
 

  resources :experiments do
    collection { get :search, to: 'experiments#index' }
  end

  resources :samples do
  collection { get :search, to: 'samples#index' }
  collection { post :advanced_search, to: 'samples#index'}
  resources :results
end
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users, except: [:create, :new]
 authenticated :user do
  root :to => 'users#index'
end

  root :to => redirect("/users/sign_in")

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :user
  has_many :parameters, dependent: :destroy
  accepts_nested_attributes_for :parameters, :reject_if => :all_blank, :allow_destroy => true
  has_many :results, dependent: :destroy
  attr_accessible :parameters_attributes, :date, :description, :name, :pic, :state, :user_id
  mount_uploader :pic, PicUploader
  STATES = ['Default', 'Out', 'Out suspect back', 'Need SEM/Raman', 'Lost']
  STATES_IN_PLACE = [['Default', 'Default'], ['Out','Out'], ['Out suspect back','Out suspect back'], ['Need SEM/Raman','Need SEM/Raman'], ['Lost', 'Lost']]
  validates_presence_of :name, :state
  has_and_belongs_to_many :experiments
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.json
  
    
  def index
  @search = Sample.search(params[:q])
  if params[:q].nil?
 @samples = @search.result(:distinct => true).order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
else
 @samples = @search.result(:distinct => true).paginate(:page => params[:page], :per_page => 10)
end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new
    @sample.state = "Default"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])
    @sample.user_id = current_user.id
    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper

	def state_class(sample)
		if sample.state == 'Out'
			'warning'
		elsif sample.state == 'Out suspect back'
			'info'
		elsif sample.state == 'Lost'
			'error'
		elsif sample.state == 'Need SEM/Raman'
			'success'
		else 
			'default'
		end
	end

	def default_pic(sample)
		if sample.pic?
			 image_tag sample.pic_url
		else
			 image_tag 'sample_def.jpg'
		end
	end

	def default_pic_index(sample)
		if sample.pic?
			 image_tag sample.pic_url(:thumb)
		else
			 image_tag 'sample_def.jpg'
		end
	end


end

app/views/samples/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:parameters, :custom_parameters, :results] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields btn btn-small btn-warning" %>
</div>

app/views/samples/_custom_parameter_fields.html.erb
<div class="nested-fields nested-cp">
	
	<%=f.inputs do %>
	 	<%=f.input :name %>
	 	<%=f.input :value %>
	 <%end%>
	 <%=link_to_remove_association "Remove custom parameter", f %>
</div>

app/views/samples/_form.html.erb
<%= semantic_form_for(@sample, html: {multipart: true}) do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs "Sample" do  %>
  
    <%= f.input :name, label: {class: "control_label"} %>
    <%= f.input :description, input_html: { rows: 8} %>
    <%= f.input :date %>
    <%= f.input :pic %>
    <%= f.input :state, as: :select, collection: Sample::STATES, include_blank: false %>
  <% end %>
  <div id="parameters_form" class="row">
  
  <%= f.semantic_fields_for :parameters do |p| %>
  <%= render 'parameter_fields', f: p %>
  <%end%>
  <div id="params-add">
    <%= link_to_add_association "Add a parameters", f, :parameters, class: 'btn btn-primary' %>
  </div>
</div>
  

  <%= f.actions do %>
    <%= f.action :submit %>
  <% end %>
<% end %>

app/views/samples/_parameter_fields.html.erb
<div class="nested-fields parameters-fields span3">
<%= f.inputs "Parameters:" do %>
<%= f.input :name %>
<%= f.input :base %>
<%= f.input :bias %>
<%= f.input :h2 %>
<%= f.input :ch4 %>
<%= f.input :b2h6h2 %>
<%= f.input :n2 %>
<%= f.input :tc %>
<%= f.input :pmw %>
<%= f.input :p %>
<%= f.input :time %>
<%= f.input :holder %>

<div id="customparameters">
<%= f.semantic_fields_for :custom_parameters do |c| %>
<%= render 'custom_parameter_fields', f: c %>
<% end %>

<%= link_to_add_association "Add custom parameter", f, :custom_parameters, class: 'btn btn-small btn-primary' %>
	<br /><br />
</div>
<%end%>


<%= link_to_remove_association "Remove this parameters", f, class: 'btn btn-danger' %>
</div>

app/views/samples/_sample.html.erb
<tr class='<%= state_class(sample) %>'>
    <td class="picture"><%= default_pic_index(sample) %></td>
    <td><%= link_to sample.name, sample %></td>
    <td><%= truncate(sample.description, length: 25) %></td>
    <td><%= sample.state %></td>
    <td><%= sample.date %></td>
    <td><%= sample.user.name %></td>
    <% if can? :destroy, Sample %>
    <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>

app/views/samples/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<div class="row-fluid">
    <div class="span8">
    <% if can? :create, Sample %>
    <%= link_to 'New Sample', new_sample_path, class: 'btn btn-info pull-right' %>
        <h2>Samples</h2>
    <%end%>
<table class="table table-bordered">
 <thead> 
    <th>Picture</th>
    <th><%= sort_link @search, :name, "Name" %></th>
    <th><%= sort_link @search, :description, "Description" %></th>
    <th><%= sort_link @search, :state, "State" %></th>
    <th><%= sort_link @search, :date, "Date" %></th>
    <th><%= sort_link @search, :user, "User" %></th>
    <th></th>
</thead>
<tbody>
<%= render @samples %>
</tbody>
</table>

<br />


</div>
<div class="span4">


<h2>Filters</h2>
<%= search_form_for @search, url: advanced_search_samples_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>

  <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
    <br />
    <%= f.submit "Search", class: 'btn btn-primary' %>
<%end%>
</div>

app/views/samples/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<div class="row-fluid">
  <div class="span8">
  <% unless @sample.parameters.empty? %>
  <h2>Parameters:</h2>
  
    <table class="table table-bordered">
     <thead>
        <th>Name</th>
        <th>Base</th>
        <th>Bias [V]</th>
        <th>H2 [Sccm]</th>
        <th>CH4 [Sccm]</th>
        <th>B2H6/H2 [Sccm]</th>
        <th>N2 [Sccm]</th>
        <th>Tc [C]</th>
        <th>Pmw [W]</th>
        <th>P [Tor]</th>
        <th>Time</th>
        <th>Holder</th>
        <th>Custom parameters</th>
      </thead>
      <tbody>
          <% @sample.parameters.each do |p| %>
          <tr><td><%= p.name %></td>
          <td><%= p.base %></td>
          <td><%= p.bias %></td>
          <td><%= p.h2 %></td>
          <td><%= p.ch4 %></td>
          <td><%= p.b2h6h2 %></td>
          <td><%= p.n2 %></td>
          <td><%= p.tc %></td>
          <td><%= p.pmw %></td>
          <td><%= p.p %></td>
          <td><%= p.time %></td>
          <td><%= p.holder %></td>
          <td><% p.custom_parameters.each do |c| %>
              <ul>
                <li><%= c.name %>: <%= c.value %></li>
              </ul>
              <%end%>
            </td></tr>
          <%end%>
      </tbody>  
</table>

<% else %>
<h2>There are no parameters for this sample in database</h2>
<%end%>
<h2>Results:</h2>
  <div id="results">
  <ul id="result-list">
    <%= render 'results/results_list' %>
  </ul>
</div>
<% if can? :create, Result %>
<div class='links'>
  <%= link_to "Add result", new_sample_result_path(@sample), remote: true, class: 'btn btn-primary' %>
</div>
<%end%>
<div id="new-result">
</div>
  </div>
  <div class="span4">
    <table class="table">
      <tr> <td colspan='2'><%= image_tag(@sample.pic_url(:show)) %> </td> </tr>
      <tr> <td colspan='2'><% if can? :menage, @sample %><%= link_to "Edit sample", edit_sample_path(@sample), class: 'btn btn-info' %> <%= link_to "Remove sample", sample_path(@sample,), method: :delete, class: 'btn btn-alert', confirm: "Are you sure?" %> <%end%>  </td></tr>
      <tr> <td class="info">Name:</td> <td class="show-description"><%= best_in_place @sample, :name %></td></tr>
      <tr> <td class="info">Date:</td> <td class="show-description"><%= @sample.date %></td></tr>
      <tr> <td class="info">State:</td> <td class="show-description"><%= best_in_place @sample, :state, type: :select, collection: Sample::STATES_IN_PLACE %></td></tr>
      <tr> <td class="info">User:</td> <td class="show-description"><%= @sample.user.name %></td></tr>
      <tr> <td class="info">Description:</td> <td class="show-description"><%= best_in_place @sample, :description, type: :textarea %></td></tr>
    </table>
  </div>
</div>