config/routes.rb
AxData::Application.routes.draw do
  
 

  resources :experiments do
    collection { get :search, to: 'experiments#index' }
  end

  resources :samples do
  collection { get :search, to: 'samples#index' }
  collection { post :advanced_search, to: 'samples#index'}
  resources :results
end
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users, except: [:create, :new]
 authenticated :user do
  root :to => 'users#index'
end

  root :to => redirect("/users/sign_in")

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role
  # attr_accessible :title, :body
  validates_presence_of :name, :email, :role
  has_many :samples
  
  ROLES = ['Super Admin', 'Admin', 'Student', 'User']
  ROLES_IN_PLACE = [['Super Admin', 'Super Admin'], ['Admin', 'Admin'], ['User', 'User'], ['Student', 'Student']]
  
  def login_mailer
    UserMailer.new_registration(self)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication
  
  def check_permissions
    authorize! :create, resource
  end

    def new
    resource = build_resource({})
  
    respond_with resource

  end

  # POST /resource
  def create
    build_resource

    if resource.save
      respond_with resource
    else
      set_flash_messages :notice, "Try again"
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html
	before_filter :authenticate_user!
  
  def index
   	@users = User.all
   	respond_with(@user)
  end

  def show
    @user = User.find(params[:id])
    respond_with_bip(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { respond_with_bip(@user) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(@user) }
      end
    end
  end

def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
 
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_users.html.erb
<% @users.each do |u| %>
   <tr>
        
        <td><%= u.name %></td>
        <td><%= mail_to "#{u.email}", u.email %></td>
        <% if current_user.role == "Super Admin" && u != current_user  %>
        <td><%= best_in_place u, :role, type: :select, collection: User::ROLES_IN_PLACE %></td>
        <% else %>
        <td><%= u.role %> </td>
        <% end %>
        <% if current_user.role == "Super Admin" %>
        <td><%= link_to "Delete user", user_path(u), method: :delete,
                                    data: { confirm: "Do you really want to destroy user #{u.email}?" } %></td>
        <%end%>
    </tr>
    <% end %>

app/views/users/index.html.erb
<div class="row-fluid">
<% if current_user.role == "Super Admin" %>
<div class="span8">
<% else %>
<div class="span12">
<%end%>
<table class="table table-striped">
     <thead>
              <tr>
            <th>User name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Delete</th>
              </tr>
    </thead>


<tbody id="users">
  <%= render 'users' %>
</tbody>
</table>
</div>

<% if current_user.role == "Super Admin" %>
<div id="new-user" class="span4">
  <%= link_to "Add user", new_user_registration_path, remote: true, class: 'btn btn-block btn-primary' %>
</div>
<%end%>
</div>