config/routes.rb
AxData::Application.routes.draw do
  
 

  resources :experiments do
    collection { get :search, to: 'experiments#index' }
  end

  resources :samples do
  collection { get :search, to: 'samples#index' }
  collection { post :advanced_search, to: 'samples#index'}
  resources :results
end
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users, except: [:create, :new]
 authenticated :user do
  root :to => 'users#index'
end

  root :to => redirect("/users/sign_in")

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :sample
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, :reject_if => :all_blank, :allow_destroy => true
  attr_accessible :description, :attachments_attributes, :name, :sample_id
  validates_presence_of :name
  
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
 
  
  def new
  	@sample = Sample.find(params[:sample_id])
  	@result = @sample.results.build
  	
  	respond_to do |format|
      format.js
    end

  end

  def create
    @sample = Sample.find(params[:sample_id])
  	@result = @sample.results.new(params[:result])
     if @result.save
      flash[:notice] = "Successfully created post."
      redirect_to sample_path(@sample)
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:sample_id])
    @result = @sample.results.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

# PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:sample_id])
    @result = @sample.results.find(params[:id])
    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:sample_id])
    @result = @sample.results.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.js
      format.json { head :no_content }
    end
  end



end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_attachment_fields.html.erb
<div class="nested-fields">
	<%=f.inputs do %>
	 	<%=f.input :file %>
	 <%end%>
	 <%=link_to_remove_association "Remove file", f %>
</div>

app/views/results/_form.html.erb
<%= semantic_form_for [@sample, @result], html: {multipart: true}  do |f| %>
    <%= f.inputs "Result" do %>
    	<%= f.input :name %>
    	<%= f.input :description, input_html: { rows: 8} %>
    	<%end%>
    	<div>
  
		  <%= f.semantic_fields_for :attachments do |p| %>
		  <%= render 'attachment_fields', f: p %>
		  <%end%>
		  
		    <%= link_to_add_association "Add file", f, :attachments, class: 'btn btn-info' %>
		  
		</div>
		<%= f.actions do %>
		<%= f.action :submit%>
		<%end%>
	<%end%>

app/views/results/_results_list.html.erb
<%@sample.results.each do |r| %>
	<li> <%= div_for(r) do %> <h4><%= r.name %></h4><p><%= r.description %></p>
		<h4>Files:</h4>
				<ul> <% r.attachments.each do |f| %>
					<li> <%= link_to f.file.file.filename, f.file.url %> </li>
					<%end%>
				</ul>
			<div id="edit-result"></div>
			<% if can? :update, Result %>
			<%= link_to "Edit result", edit_sample_result_path(@sample,r), remote: true, class: 'btn btn-small btn-info' %>
			<%end%>
			<% if can? :destroy, Sample %>
			<%= link_to "Remove result", sample_result_path(@sample,r), method: :delete, remote: true, class: 'btn btn-small btn-error', confirm: "Are you sure?" %> 
			<%end%>
			 <%end%></li>
<%end%>

app/views/results/destroy.js.erb
$('#<%=dom_id(@result) %>').parent('li').remove();

app/views/results/edit.js.erb
$('#<%=dom_id(@result) %> #edit-result').html("<%= escape_javascript( render(:partial => 'results/form') ) %>");

app/views/results/new.js.erb
$('#new-result').html("<%= escape_javascript( render(:partial => 'results/form') ) %>");