config/routes.rb
AxData::Application.routes.draw do
  
 

  resources :experiments do
    collection { get :search, to: 'experiments#index' }
  end

  resources :samples do
  collection { get :search, to: 'samples#index' }
  collection { post :advanced_search, to: 'samples#index'}
  resources :results
end
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users, except: [:create, :new]
 authenticated :user do
  root :to => 'users#index'
end

  root :to => redirect("/users/sign_in")

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  attr_accessible :description, :name, :sample_ids
  has_and_belongs_to_many :samples
  accepts_nested_attributes_for :samples
  validates_presence_of :name
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  # GET /experiments
  # GET /experiments.json
  def index
    @search = Experiment.search(params[:q])
      if params[:q].nil?
     @experiments = @search.result(:distinct => true).order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    else
     @experiments = @search.result(:distinct => true).paginate(:page => params[:page], :per_page => 10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiments }
    end
  end

  # GET /experiments/new
  # GET /experiments/new.json
  def new
  @experiment = Experiment.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experiment }
    end
  end

  # GET /experiments/1/edit
  def edit
    @experiment = Experiment.find(params[:id])
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(params[:experiment])

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to experiments_path, notice: 'Experiment was successfully created.' }
        format.json { render json: @experiment, status: :created, location: @experiment }
      else
        format.html { render action: "new" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiments/1
  # PUT /experiments/1.json
  def update
    @experiment = Experiment.find(params[:id])

    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to experiments_path, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy

    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_condition_fields.html.erb
<div class="field">

<%= f.collection_select :samples_name_cont, Sample.all, :name, :name %>

</div>

app/views/experiments/_form.html.erb
<%= semantic_form_for @experiment do |f| %>
  <%= f.inputs "New experiment" do %>
    <%= f.input :name %>
    <%= f.input :description, input_html: { rows: 8} %>
    <%end%>
    <%=f.inputs "Samples" do%>
    
    <%= f.input :samples, label: false,  :as => :select,  :collection => Sample.all, wrapper_html: { id: "samples_collection"} %>
    <%end%>
  <%= f.actions do %>
   <%= f.action :submit %>
  <%end%>
<%end%>

app/views/experiments/edit.html.erb
<%= render 'form' %>


<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<div class="row-fluid">
<div class="span8">
  <% if can? :create, Experiment %>
<%= link_to 'New Experiment', new_experiment_path, class: 'btn btn-info pull-right' %>
<%end%>
<h2>Experiments:</h2>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Samples</th>
    <th></th>
    <th></th>
  </tr>

<% @experiments.each do |experiment| %>
  <tr>
    <td><%= experiment.name %></td>
    <td><%= best_in_place experiment, :description, type: :text_area %></td>
    <td><ul><% experiment.samples.each do |s| %>
        <li><%=link_to s.name, sample_path(s) %></li>
        <%end%></ul>
    <td><% if can? :update, experiment %><%= link_to 'Edit', edit_experiment_path(experiment) %> <% end %></td>
    <td><% if can? :destroy, Sample %><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %><%end%></td>
  </tr>
<% end %>
</table>
</div>
<div class="span4">
  <%= semantic_search_form_for @search do |f| %>
    <%= f.inputs "Filter experiments" do %>
      <%= f.input :name_cont, label: "Name:" %>
      <%= f.input :samples_name_eq_any, label: "Samples:", as: :check_boxes, collection: Sample.all.map(&:name) %>
    <%end%>
  <%= f.actions do %>
  <%= f.action :submit %>
  <%end%>
<% end %>
</div>
</div>

app/views/experiments/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', experiments_path %>